In [2]:
import tensorflow as tf
import numpy as np

amplifier = 1
threshold_percentage = 20

# Load the pre-trained model
model = tf.keras.models.load_model('MNIST_vgg16_0&1.h5')

# Copy the structure and parameters of the model
freezing_value_mnist = tf.keras.models.clone_model(model)
freezing_value_mnist.set_weights(model.get_weights())

# Modify the weights as specified
for layer in freezing_value_mnist.layers:
    if len(layer.get_weights()) > 0:
        weights = layer.get_weights()
        new_weights = []

        for weight_matrix in weights:
            # Compute the biggest weight magnitude in the whole layer
            max_magnitude = np.max(np.abs(weight_matrix))
            
            # Apply the transformation to each weight
            new_weight_matrix = 1 - (np.abs(weight_matrix) / max_magnitude) ** amplifier
            new_weights.append(new_weight_matrix)

        # Set the new weights
        layer.set_weights(new_weights)

# Further modify the weights by setting the smallest 20% weights for each layer to 0
for layer in freezing_value_mnist.layers:
    if len(layer.get_weights()) > 0:
        weights = layer.get_weights()
        new_weights = []

        for weight_matrix in weights:
            # Flatten the weight matrix and sort the weights by magnitude
            flat_weights = weight_matrix.flatten()
            threshold = np.percentile(np.abs(flat_weights), threshold_percentage)
            
            # Set the smallest 20% weights to 0
            new_weight_matrix = np.where(np.abs(weight_matrix) < threshold, 0, weight_matrix)
            new_weights.append(new_weight_matrix)

        # Set the new weights
        layer.set_weights(new_weights)

# Print all the weights in the model
for layer in freezing_value_mnist.layers:
    if len(layer.get_weights()) > 0:
        weights = layer.get_weights()
        print(f"Weights for layer {layer.name}:")
        for weight_matrix in weights:
            print(weight_matrix)

# Save the modified model
freezing_value_mnist.save('freezing_value_mag_0&1_20%_^1.h5')

print("Model 'freezing_value_mag_0&1_20%_^1.h5' has been saved.")


2024-08-03 17:31:59.141207: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-03 17:31:59.157378: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-03 17:31:59.176876: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-03 17:31:59.182771: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-03 17:31:59.196951: I tensorflow/core/platform/cpu_feature_guar

Weights for layer conv2d:
[[[[0.75747746 0.         0.46589136 ... 0.23409325 0.47354937
    0.99253917]
   [0.6088927  0.2247445  0.27462202 ... 0.26016164 0.
    0.78857666]
   [0.8989447  0.2410605  0.99966794 ... 0.56626886 0.89184767
    0.99701935]]

  [[0.9792113  0.7896273  0.5475897  ... 0.5207259  0.8678351
    0.        ]
   [0.         0.3884374  0.38706398 ... 0.7760576  0.4872111
    0.8907181 ]
   [0.         0.77071035 0.83925813 ... 0.93471247 0.45251358
    0.7562719 ]]

  [[0.62099683 0.9046538  0.         ... 0.         0.
    0.6518841 ]
   [0.3113674  0.         0.29762477 ... 0.26519918 0.44967818
    0.703169  ]
   [0.29947853 0.8104612  0.93235326 ... 0.7884387  0.5909982
    0.        ]]]


 [[[0.90285534 0.69044924 0.38765407 ... 0.61972374 0.
    0.5464788 ]
   [0.         0.9285266  0.3013795  ... 0.9309204  0.
    0.8847773 ]
   [0.39446557 0.         0.87166053 ... 0.6517609  0.8559101
    0.34210986]]

  [[0.7021071  0.3228938  0.         ... 0.         

Weights for layer dense:
[[0.         0.9186381  0.97356325 ... 0.5363826  0.8814423  0.6674911 ]
 [0.90850484 0.92205393 0.         ... 0.81596684 0.90973264 0.82446146]
 [0.6388496  0.7027106  0.8404632  ... 0.9718022  0.6512563  0.68024313]
 ...
 [0.6837096  0.515656   0.49887526 ... 0.97628593 0.6878892  0.6353704 ]
 [0.573854   0.8037625  0.83908635 ... 0.4926771  0.49983984 0.        ]
 [0.5135568  0.5808629  0.7318748  ... 0.76310176 0.8785161  0.7878538 ]]
[0.93596226 0.9967749  0.         ... 0.8112811  0.         0.        ]
Weights for layer dense_1:
[[0.7909518  0.44376552 0.80158114 ... 0.8526418  0.         0.39421666]
 [0.51101345 0.461021   0.4054014  ... 0.         0.8374863  0.        ]
 [0.         0.51232374 0.         ... 0.5335517  0.50288206 0.91605747]
 ...
 [0.6196402  0.         0.6237903  ... 0.60915726 0.4404416  0.62139595]
 [0.5939795  0.6296104  0.508888   ... 0.41742003 0.3567239  0.32468176]
 [0.7405529  0.8760209  0.         ... 0.6220953  0.         0